spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:tcp://localhost/~/Workspace/h2-data/spring
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:

        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    restart:
      enabled: true
      quiet-period: 1s
      poll-interval: 2s
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace


    #  spring.devtools.livereload.enabled=true
    #  spring.resources.static-locations=file:src/main/resources/static/
    #  spring.thymeleaf.cache=false
    #  spring.thymeleaf.prefix=file:src/main/resources/templates/
